### ISSUE TITLE
ValueError: URL must include a 'scheme', 'host', and 'port' component (ie 'https://localhost:9200')

### ISSUE THREAD

**Issue by homaonchij** [WHUIR/MGNM#1]
Thank you very much for your outstanding contribution! Running 'train Py 'file: valueerror: URL must include a'scheme','host', and'port' component (ie ' https://localhost:9200 ')。 How to solve it? Thank you again.

**Comment by lichenliang-whu** [comment]
We did not use the elastic search module. Just ignore it.

**Comment by wy-0** [comment]
我是将elasticUtil.py文件里的self.es = Elasticsearch('172.28.6.8:9200')改为self.es = Elasticsearch('https://172.28.6.8:9200')，这一部分就不报错了。但是model中的118行”loss = model.train(sess, [user, tgt, hist, mask, label, LEARNING_RATE])“，报错tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [256] vs. [252]
         [[{{node gradients/logistic_loss_3/mul_grad/BroadcastGradientArgs}}]]
